name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: build backend
            run: |
                cd backend
                docker build -t backend .

          - name: build frontend
            run: |
                cd frontend
                docker build -t frontend .

          - name: deploy to azure vm
            uses: appleboy/ssh-action@v0.1.7
            with:
              host: ${{ secrets.AZURE_VM_IP }}
              username: ${{ secrets.AZURE_VM_USER }}
              key: ${{ secrets.AZURE_VM_SSH_KEY }}
              script: |
                echo "Current directory: $(pwd)"
                echo "Home directory: $HOME"
                echo "Contents:"
                ls -la $HOME
                cd $HOME/Task-app-azure
                export MONGO_URI=${{ secrets.MONGO_URI }}
                sudo docker-compose down || true
                sudo docker stop $(sudo docker ps -q) 2>/dev/null || true
                sudo docker rmi nginx:latest 2>/dev/null || true
                sudo docker container prune -f
                sudo docker image prune -f
                sudo docker-compose pull
                sudo docker-compose up -d --build