name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: build backend
            run: |
                cd backend
                docker build -t backend .

          - name: build frontend
            run: |
                cd frontend
                docker build -t frontend .

          - name: deploy to azure vm
            uses: appleboy/ssh-action@v0.1.7
            with:
              host: ${{ secrets.AZURE_VM_HOST }}
              username: ${{ secrets.AZURE_VM_USERNAME }}
              key: ${{ secrets.AZURE_VM_SSH_KEY }}
              script: |
                cd /home/azureuser/task-app
                docker-compose pull
                docker-compose up -d --build